cart/urls.py
from django.urls import path
from . import  views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('delete/<int:product_id>/',views.delete,name='delete')
]
 

search_app/urls.py
from django.urls import path 
from . import views

app_name='search_app'
urlpatterns = [
    path('',views.SearchReslut,name='SearchResult'),
]

shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopapp/',include('shopapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]

shopapp/urls.py
from django.urls import path,include
from . import views
app_name='shopapp'

urlpatterns = [

    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail'),

]

cart/models.py
from django.db import models
from shopapp.models import Product


class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True,null=True)
    date_added=models.DateField(auto_now_add=True,null=True)
    
    class Meta:
        db_table='Cart'
        ordering=['date_added']
        
    def __str__(self):
        return '{}'.format (self.cart_id)
    
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE,null=True)
    quantity=models.IntegerField(null=True)
    active=models.BooleanField(default=True,null=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return '{}'.format (self.product)
    
        

search_app/models.py
from django.db import models

# Create your models here.

shopapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200,unique=True)
    slug=models.SlugField(max_length=200,unique=True)
    des=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
        
    def get_url(self):
        return reverse('shopapp:products_by_category',args=[self.slug])
    
    def __str__(self):
        return '{}'.format(self.name)
    
class Product(models.Model):
        category=models.ForeignKey(Category,on_delete=models.CASCADE)
        name=models.CharField(max_length=200,unique=True)
        slug=models.SlugField(max_length=200,unique=True)
        des=models.TextField(blank=True)
        image=models.ImageField(upload_to='product',blank=True)
        price=models.DecimalField(max_digits=10,decimal_places=2)
        stock=models.IntegerField()
        available=models.BooleanField(default=True)
        created=models.DateTimeField(auto_now_add=True)
        updated=models.DateTimeField(auto_now=True)
        
        def get_url(self):
            return reverse('shopapp:prodCatdetail',args=[self.category.slug,self.slug])
        
        class Meta:
            ordering=('name',)
            verbose_name='product'
            verbose_name_plural='products'
            
        def __str__(self):
            return '{}'.format(self.name)
    
        
    

cart/views.py
from django.shortcuts import render, redirect , get_object_or_404
from shopapp . models  import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
        return cart
    
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
        
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
       
        for cart_item  in  cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
    
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def delete(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')
    
    

search_app/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q
# Create your views here.

def SearchReslut(request):
    products=None
    query=None
    if  'q'  in request.GET:
        query = request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) |  Q(des__contains=query))
        return render(request,'search.html',{'query':query,'products':products})
        

shopapp/views.py
from django.shortcuts import render, get_object_or_404
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


def allProdCat(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,8)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
        
    return render(request,"category.html",{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product })
        

templates/base.html
{% load static %}

 <html>
    <head>
        <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <meta name="description" content="{% block metadescription %} {% endblock %}">

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a5d3a2490b.js" crossorigin="anonymous"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  
    {% block title %} {% endblock %}
    </head>
    <body style="background-color: skyblue">
        <div>
            {% include 'navbar.html ' %}
        <div class="container">
        {% include 'header.html ' %}
        {% block content %}
        {% endblock %}
        </div>
    </div>
    
        {% include 'footer.html ' %}
    <script src="{% static ' js/popper.min.js' %} "></script>
    <script src="{% static ' js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
                CART PAGE......................
{% endblock %}
{% block title %}
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping cart is empty.....
        </h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'shopapp:allProdCat' %}">Here</a>to continue shopping.
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
<br>
<h1 class="text-center my_title">
    Your Shopping cart
</h1>
<br>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                        <th colspan="5">
                            Your Items
                        </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url"> <img src="{{ cart_item.product.image.url }}" width="200px;" height="200px;"  alt=""  class="float-left rounded custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{ cart_item.product.name }}
                        <br>
                        SKU : {{ cart_item.product.id }}
                        <br>
                        Price : $ {{ cart_item.product.price }}
                        <br>
                        Qty : {{ cart_item.quantity }} x $ {{ cart_item }}
                    </td>
                    <td>
                        $ {{ cart_item.sub_total }}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}"       class="custom_a">    <i class="fa fa-plus custom_icon">
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">    <i class="fa fa-minus custom_icon"></a></i></a>
                        <a href="{% url 'cart:delete' cart_item.product.id %}"           class="custom_icon"><i class="fa fa-trash custom_icon"></a></i></a>
                    </td>
                    {% else %}
                    <td>
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></a></i></a>
                        <a href="{% url 'cart:delete' cart_item.product.id %}" class="custom_icon">     <i class="fa fa-trash custom_icon"></a></i></a>
                    </td>
                    {% endif %}
                    <tr>
                 {% endfor %}

                </tbody>
            </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
        </thead>
        <tr>
        <td>
            Please review your cart before order
            <td>
            </tr>
            <tr>
                <td class="text-left">
                    Total Amound : <strong> {{total }} </strong>
                </td>
            </tr>
            <tbody>
            </table>

            <div class="mx-auto">
                <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-primary btn-block my_custom_button">Pay</a>
            </div>
            <div class="mx-auto">
                <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-warning btn-block my_custom_button">Countinu Shopping</a>
            </div>
                {% endif %}
</div>            
</div>            
</div>
{% endblock %} 

templates/category.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}

    {% if category %}
        {{ category.description| truncatewords:155 }}
    {% else %}
            Welcome to Codiac store...............
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}

    {% endif %}
{% endblock %}

{% block content  %}
        {% if category %}

<div>
    <div class="row my_row_class">
        <div class="mx-auto">
        <p><a href="{% url 'shopapp:allProdCat' %}"> Our Product Collections </p>
    </div>
</div>
</div>
        {% endif %}

<div class="mx_auto">
    {% if category %}
    <img class="my_image my_image_padding" src="{{category.image.url}}" width="200px;" height="200px;" alt="{{ category.name }}" >
</div>
<br>
<div> 
    <h1 class="text-center my_title"> {{ category.name }} </h1>
    <p class="text-justify"> {{ category.des }} </p>
</div>
    {% else %}
    <div>
        <img  class="my_image my_image_padding" src="{% static 'img/banner.jpg' %}"  alt="Our Product">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title"> Our Products Collections </h1>
        <p class="text-justify">  Certaines personnes sont susceptibles de faire des crises d'épilepsie
             ou d'avoir des pertes de conscience à la vue de certains types de
            lumières clignotantes ou d'éléments fréquents dans notre 
            environnement quotidien. Ces personnes s'exposent à des crises 
            lorsqu'elles regardent certaines images télévisées ou lorsqu'elles
            jouent à certains jeux vidéo. Ces phénomènes peuvent apparaître 
            alors même que le sujet n'a pas d'antécédent médical ou n'a jamais
            été confronté à une crise d'épilepsie. Si vous (ou un membre de votre
            famille) avez déjà présenté des symptômes liés à l'épilepsie
            (crise ou perte de conscience) en présence de stimulations lumineuses,
            veuillez consulter votre médecin avant toute utilisation.</p>
        </div>
    {% endif %}

    <div class="container">
        <div class="row mx-auto">
            {% for product in products.object_list %}
                <div class="col-6 col-md-4 col-lg-3 mb-3">
                    <div class="card" style="width: 100%;">
                        <a href="{{ product.get_url }}">
                            <img class="card-img-top my_image" src="{{ product.image.url }}" style="width: 100%; height: 200px;" alt="{{ product.name }}">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">{{ product.name }}</h4>
                            <p class="card-text">{{ product.price }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
  
<div class="mx-auto">
    {% if products.paginator.num_pages > 1 %}
    <hr>
    <div class="text-center">
        {% for pg in products.paginator.page_range %}
                <a href="?page={{ pg }}"  class="btn btn-light btn-sm" {% if products.number == pg %} active {% endif %}>{{ pg }}</a>
        {% endfor %}
        </div>
    {% endif %} 
    
    </div>
    <br>
</div>

{% endblock %} 

templates/footer.html
<div class="footer navbar-fixed-bottom  my_footer">
    <p class="text-center"><b>@copy- Codica  Tech Private Limited </b></p>
</div>

templates/header.html
{% load static %}
<header><br>
    <center>
        <href="{% url 'shopapp:allProdCat' %}">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Overwatch_circle_logo.svg/600px-Overwatch_circle_logo.svg.png"
         alt="logimage" width="80px;" height="80px;">
    </center>
</header>
<br><br>

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Travel pro</title>
    <meta content="width=device-width, initial-scale=1.0 " name="viewport">
    <meta content="Free HTML Templates " name="keywords">
    <meta content="Free HTML Templates " name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico ' %}" rel="icon " >

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com ">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&family=Roboto:wght@400;700&display=swap ' %}" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css " rel="stylesheet">
    <link href=" https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css " rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css ' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css ' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css ' %}" rel="stylesheet">

    <style>
        .team-item {
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 30px; /* Add some space between each team item */
        }
        .team-text {
            padding: 20px;
            background-color: #fff;
        }
        .team-text h4 {
            font-size: 20px;
            margin-bottom: 10px;
        }
        .team-text span {
            font-size: 16px;
            color: #777;
        }
        .team-item img {
            width: 100%; /* Make the image fill the entire width of its container */
            height: auto; /* Maintain aspect ratio */
            display: block; /* Remove any extra space below the image */
        }
    </style>

</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid bg-primary d-none d-lg-block">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-lg-start mb-2 mb-lg-0">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-dark py-2 pe-3 border-end border-white" href=""><i class="bi bi-telephone text-secondary me-2"></i>+012 345 6789</a>
                        <a class="text-dark py-2 px-3" href=""><i class="bi bi-envelope text-secondary me-2"></i>info@example.com</a>
                    </div>
                </div>
                <div class="col-md-6 text-center text-lg-end">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-body py-2 px-3 border-end border-white" href="">
                            <i class="fab fa-facebook-f text-secondary"></i>
                        </a>
                        <a class="text-body py-2 px-3 border-end border-white" href="">
                            <i class="fab fa-twitter text-secondary"></i>
                        </a>
                        <a class="text-body py-2 px-3 border-end border-white" href="">
                            <i class="fab fa-linkedin-in text-secondary"></i>
                        </a>
                        <a class="text-body py-2 px-3 border-end border-white" href="">
                            <i class="fab fa-instagram text-secondary"></i>
                        </a>
                        <a class="text-body py-2 ps-3" href="">
                            <i class="fab fa-youtube text-secondary"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark shadow-sm px-5 py-3 py-lg-0">
        <a href="index.html" class="navbar-brand p-0">
            <h1 class="m-0 text-uppercase text-primary"><i class="fa fa-paint-roller text-secondary me-3"></i>Places</h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            {% comment %} {% if user.is_authenticated %} {% endcomment %}
            <div class="navbar-nav ms-auto py-0 pe-4 border-end border-5 border-primary">
                <a href="Welcome " class="nav-item nav-link active">{{user.username}}</a>
                <a href="credapp/login" class="nav-item nav-link">Login</a>
                <a href="credapp/logout" class="nav-item nav-link">Logout</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"></a>
                    <div class="dropdown-menu m-0">
                        <a href="blog.html" class="dropdown-item">Blog Grid</a>
                        <a href="detail.html" class="dropdown-item">Blog Detail</a>
                        <a href="team.html" class="dropdown-item">The Team</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                    </div>
                </div>
                <a href="credapp/reg" class="nav-item nav-link">Register</a>
            </div>
            <div class="d-none d-lg-flex align-items-center ps-4">
                <i class="fa fa-2x fa-mobile-alt text-secondary me-3"></i>
                <div>
                    <h5 class="text-primary mb-1"><small>Call Now</small></h5>
                    <h6 class="text-light m-0">+012 345 6789</h6>
                    {% comment %} {% endif %} {% endcomment %}
                </div>
            </div>
        </div>
    </nav>
    <!-- Navbar End -->
<br><br><br>

<!-- Team Start -->
<div class="container-fluid">
    <div class="row">
        {% for i in result %}
        <div class="col-md-4 mb-4"> <!-- Adjust the column width and add margin -->
            <div class="team-item">
                <img class="img-fluid" src="{{ i.img.url }}" alt="{{ i.name }}">
                <div class="team-text">
                    <div class="mt-auto mb-3">
                        <h4 class="mb-1">{{ i.name }}</h4>
                        <span class="text-uppercase">{{ i.desc }}</span>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- Team End -->



    <!-- Footer Start -->
    <div class="container-fluid bg-dark bg-footer text-light py-2">
        <div class="container py-5">
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-primary text-dark py-4">
        <div class="container">
            <div class="row g-0">
                <div class="col-md-6 text-center text-md-start">
                    <p class="mb-md-0">Copyright &copy; <a class="text-dark fw-bold" href="#">Your Site Name</a>. All Rights Reserved.</p>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <p class="mb-0">Designed by <a class="text-dark fw-bold" href="#">Ambroz72</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-secondary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>

templates/product.html
{% extends "base.html" %}
{% load static %}

{% block metadescription %}
    {{ product.description|truncatewords:150 }}
{% endblock %}

{% block title %}
    {{ product.name }} - Codiac Store
{% endblock %}

{% block content %}
<div class="container my-4">
    <div class="row">
        <div class="col-md-6">
            <div class="text-center">
                <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.name }}">
            </div>
        </div>
        <div class="col-md-6">
            <div class="text-center">
                <h1 class="my-4">{{ product.name }}</h1>
                <p class="lead">Rs{{ product.price }}</p>
                <hr>
                <h2 class="my-3">Product Description</h2>
                <p class="text-justify">{{ product.des }}</p>
                {% if product.stock <= 0 %}
                    <p class="text-danger">Out of stock</p>
                {% else %}
                    <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-primary">Add to Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}

We have various products...
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for :<b>"{{query}}"</b> </p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="col-4">
            {% comment %} <div class="card"> {% endcomment %}
                <div class="card-body">
        <div class="my_bottom_margi col-9   col-sm-12   col-md-4   col-md-4   xol-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{ product.get_url }}"><img class="card-img-top my_image" src="{{ product.image.url }}" width="200px;" height="200px;"  alt="{{ product.name }}"></a>
              <div class="card-body">
                <h4>{{ product.name }} </h4>
                <p> {{ product.price }} </p>
              </div>
            </div>
                    </div>
                {% comment %} </div> {% endcomment %}
    </div>
</div>  
</div>
</div>
{% empty %}
<div class="row mx-auto">
    <p class="text-center my_search_text"> 0 result found </p>
</div>
{% endfor %}

{% endblock %}